### PR TITLE
Add option to reuse socket between sends.

### PR DESCRIPTION
**Pull request by jmhobbs**
Experimental feature, solves #25.

Not 100% solid on this, it needs more review, testing and discussion.

It's got the bare minimum HTTP parsing to use `keep-alive`.  There isn't much in the way of a safety net.

### CODE REVIEW

**Comment by jmhobbs** [comment]
Also, I verified that it's working with `ssldump`

```shell
jmhobbs@venera:~ ✪ cat ssl.log | grep New
New TCP connection #1: venera(60825) <-> iq-in-f108.1e100.net(993)
New TCP connection #2: venera(60955) <-> email.us-east-1.amazonaws.com(443)
New TCP connection #3: venera(61152) <-> iq-in-f108.1e100.net(993)
jmhobbs@venera:~ ✪
```

**Comment by ovr** [comment]
ping @jmhobbs

**Comment by jmhobbs** [comment]
I'm still not comfortable making this big of a change without deeper testing.  In the meantime, you can edit your `composer.json` to require this branch, and feedback is very welcome.

```
"require": {
  "jmhobbs/swiftmailer-transport-aws-ses": "dev-feature/persistent-connections as 0.9.2"
}
```
I'm adding some documentation to the README on master linking to this as a recommendation.

**Comment by jmhobbs** [comment]
As I referenced in #31, if anyone can provide feedback on large scale sending with this branch, it is appreciated.  I don't want to merge unless I have some evidence it isn't breaking things.

**Pull request merged**
